/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.print.Collation;
import javax.swing.DefaultButtonModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.DBModel;
import model.IModel;
import model.Kerdes;

/**
 *
 * @author Csaba Ödön <your.name at your.org>
 */
public class Foablak extends javax.swing.JFrame {

    private IModel model;
    private Vector<Kerdes> kerdesek;
    private boolean init;
    private Kerdes aktKerdes;
    private int szamlalo = 15;
    private int kerdesIndex = 0;

    public Foablak() {
        initComponents();

        setLocationRelativeTo(null);
        setTitle("Legyen Ön is milliomos!");

        String userName = "root";
        String password = "1234";
        String db_url = "jdbc:mysql://localhost:3306/loim";

        Connection conn;
        setVisible(true);

        try {
            conn = DriverManager.getConnection(db_url, userName, password);
            model = new DBModel(conn);
            Vector<Kerdes> kerdesek = model.getKerdes();
            Collections.shuffle(kerdesek);

        } catch (SQLException ex) {
            hibaAblak(ex);
        }
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        btnValasz1 = new javax.swing.JButton();
        btnValasz2 = new javax.swing.JButton();
        btnValasz3 = new javax.swing.JButton();
        jKerdes = new javax.swing.JLabel();
        btnValasz0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "15. 40 000 000", "14. 20 000 000", "13. 10 000 000", "12. 5 000 000", "11. 3 000 000", "10. 1 500 000", "9. 800 000", "8. 500 000", "7. 300 000", "6. 200 000 ", "5. 100 000", "4. 50 000", "3. 25 000", "2. 10 000", "1. 5 000" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.setDropMode(javax.swing.DropMode.ON);
        jScrollPane1.setViewportView(jList1);

        btnValasz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz1ActionPerformed(evt);
            }
        });

        btnValasz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz2ActionPerformed(evt);
            }
        });

        btnValasz3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz3ActionPerformed(evt);
            }
        });

        jKerdes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jKerdes.setLabelFor(this);

        btnValasz0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValasz2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnValasz0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValasz3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnValasz1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jKerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jKerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnValasz0, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(btnValasz1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnValasz3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(btnValasz2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValasz0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz0ActionPerformed

        aktKerdes = kerdesek.get(kerdesIndex);
        int joValasz = aktKerdes.getHelyesValasz();
        if (joValasz==aktKerdes.getHelyesValasz()) {

            ujKerdes();
//            szamlalo--;

            Collections.shuffle(kerdesek);

//            init();
           elenorzes(0);
        } else {
            JOptionPane.showMessageDialog(this, "Vége a játéknak...",
                    "Vége", JOptionPane.INFORMATION_MESSAGE);
        }
////              kilepes();
    }//GEN-LAST:event_btnValasz0ActionPerformed

    private void btnValasz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz1ActionPerformed
        aktKerdes = kerdesek.get(kerdesIndex);
        int joValasz = aktKerdes.getHelyesValasz();
        if (joValasz == aktKerdes.getHelyesValasz()) {
            
            ujKerdes();
//            szamlalo--;
            Collections.shuffle(kerdesek);

//            init();
            elenorzes(1);
        } else {
            JOptionPane.showMessageDialog(this, "Vége a játéknak...",
                    "Vége", JOptionPane.INFORMATION_MESSAGE);
        }
////              kilepes();
    }//GEN-LAST:event_btnValasz1ActionPerformed

    private void btnValasz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz2ActionPerformed
        aktKerdes = kerdesek.get(kerdesIndex);
        int joValasz = aktKerdes.getHelyesValasz();
        if (joValasz == aktKerdes.getHelyesValasz()) {

            ujKerdes();
//            szamlalo--;
            Collections.shuffle(kerdesek);

//            init();
           elenorzes(2);
        } else {
            JOptionPane.showMessageDialog(this, "Vége a játéknak...",
                    "Vége", JOptionPane.INFORMATION_MESSAGE);
        }
////              kilepes();
    }//GEN-LAST:event_btnValasz2ActionPerformed

    private void btnValasz3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz3ActionPerformed
        aktKerdes = kerdesek.get(kerdesIndex);
        int joValasz = aktKerdes.getHelyesValasz();
        if (joValasz == aktKerdes.getHelyesValasz()){

            ujKerdes();
//            szamlalo--;
            Collections.shuffle(kerdesek);

//            init();
          elenorzes(3);
        } else {
            JOptionPane.showMessageDialog(this, "Vége a játéknak...",
                    "Vége", JOptionPane.INFORMATION_MESSAGE);
        }
////              kilepes();
    }//GEN-LAST:event_btnValasz3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValasz0;
    private javax.swing.JButton btnValasz1;
    private javax.swing.JButton btnValasz2;
    private javax.swing.JButton btnValasz3;
    private javax.swing.JLabel jKerdes;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void hibaAblak(SQLException ex) {
        JOptionPane.showMessageDialog(null, ex.toString(), "Hiba történt",
                JOptionPane.ERROR_MESSAGE);
    }

    private void init() {
        try {
            kerdesek = model.getKerdes();

            for (int i = 0; i < kerdesek.size(); i++) {
                jKerdes.setText(kerdesek.get(i).getKerdes());
                btnValasz0.setText(kerdesek.get(i).getValasz0());
                btnValasz1.setText(kerdesek.get(i).getValasz1());
                btnValasz2.setText(kerdesek.get(i).getValasz2());
                btnValasz3.setText(kerdesek.get(i).getValasz3());
                i++;
                init = true;
            }

        } catch (SQLException ex) {
            hibaAblak(ex);
        }

    }

    private void ujKerdes() {
        aktKerdes = kerdesek.get(kerdesIndex);
        jKerdes.setText(aktKerdes.getKerdes());
        btnValasz0.setText(aktKerdes.getValasz0());
        btnValasz1.setText(aktKerdes.getValasz1());
        btnValasz2.setText(aktKerdes.getValasz2());
        btnValasz3.setText(aktKerdes.getValasz3());
        jList1.setSelectedIndex(szamlalo);
        kerdesIndex++;
        szamlalo--;

    }

    public void kilepes() {
        try {
            model.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(),
                    "Adatbázis hiba", JOptionPane.ERROR_MESSAGE);
            System.exit(-1);
        }
        System.exit(0);
    }

    public void elenorzes(int valasz) {
        aktKerdes = kerdesek.get(kerdesIndex);
        valasz = aktKerdes.getHelyesValasz();
        int helyes = aktKerdes.getHelyesValasz();
        String hv= "";
        switch (helyes){
            case 0:
                hv = "valasz0";
                break;
            case 1:
                hv = "valasz1";
                break;
            case 2:
                hv = "valasz2";
                break;
            case 3:
                hv= "valasz3";
                break;
            default:
                hv = "";
        }
        if (valasz == helyes) {
//            ujKerdes();
        }

    }

}
